"""Losses for the report-faithful TrajSafe-Diffuser (report section 25).

    L = lambda_traj   * L_traj
      + lambda_coarse * L_coarse
      + lambda_smooth * L_smooth
      + lambda_topo   * L_topo
      + lambda_E      * L_E
      + lambda_iou    * L_iou
      + lambda_safe   * L_safe

with

    L_E = (2 * L_center + 4 * L_shape) / 6

Explicitly removed relative to the previous V3: L_gap, L_area, L_ratio,
L_inside and the extra L_align.  ``L_center`` supervises the centre generated by
``c_i = Gamma(s_i)`` and therefore gives the Progress Head its geometric
gradient; it is not a centre-head regression.
"""

from __future__ import annotations

import math

import torch
import torch.nn.functional as F

from src.geometry.ellipse_raster import ellipse_soft_mask
from src.losses.v2_losses import trajectory_smoothness_loss

__all__ = [
    "trajectory_smoothness_loss",
    "trajectory_x0_loss",
    "topology_ce",
    "ellipse_center_loss",
    "ellipse_shape_loss",
    "ellipse_iou_loss",
    "ellipse_safety_loss",
]


def _masked_mean(values: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    """Mean over the valid ENTRIES; the mask broadcasts over trailing dims."""
    mask = mask.to(values.dtype)
    while mask.dim() < values.dim():
        mask = mask.unsqueeze(-1)
    mask = mask.expand_as(values)
    return (values * mask).sum() / mask.sum().clamp_min(1.0)


def trajectory_x0_loss(p_hat: torch.Tensor, p_gt: torch.Tensor) -> torch.Tensor:
    """MSE on the interior waypoints (endpoints are hard-conditioned)."""
    return F.mse_loss(p_hat[:, 1:-1], p_gt[:, 1:-1])


def topology_ce(pi: torch.Tensor, best: torch.Tensor,
                sample_mask: torch.Tensor) -> torch.Tensor:
    """L_topo = CE(pi, m*) with m* = argmin_m nDTW(P0, S_m)."""
    log_pi = torch.log(pi.clamp_min(1e-12))
    per = -log_pi.gather(1, best[:, None].long()).squeeze(1)
    return _masked_mean(per, sample_mask)


def ellipse_center_loss(center: torch.Tensor, center_gt: torch.Tensor,
                        sample_mask: torch.Tensor) -> torch.Tensor:
    """L_center = 1/H sum_i ||c_i - c_i^*||^2.

    ``c_i = Gamma(s_i)`` is differentiable with respect to the progress head, so
    this is the main geometric supervision of the Progress Head.
    """
    per = ((center - center_gt) ** 2).sum(dim=-1)                # [B,H]
    return _masked_mean(per, sample_mask)


def ellipse_shape_loss(shape4: torch.Tensor, shape4_gt: torch.Tensor,
                       shape_valid: torch.Tensor,
                       sample_mask: torch.Tensor) -> torch.Tensor:
    """L_shape = 1/N_valid sum_{valid} ||shape_i - shape_i^*||^2."""
    per = ((shape4 - shape4_gt) ** 2).mean(dim=-1)               # [B,H]
    valid = shape_valid & sample_mask[:, None]
    return _masked_mean(per, valid)


def ellipse_iou_loss(center: torch.Tensor, a: torch.Tensor, b: torch.Tensor,
                     theta: torch.Tensor, gt_mask: torch.Tensor,
                     shape_valid: torch.Tensor, sample_mask: torch.Tensor,
                     raster_res: int = 64, tau: float = 10.0,
                     eps: float = 1e-6) -> torch.Tensor:
    """Fuzzy soft-IoU loss on the complete ellipse, only where a label exists.

    The prediction is rasterised with the SAME soft rasteriser that produced the
    GT mask offline.
    """
    pred = ellipse_soft_mask(center, a, b, theta, int(raster_res), float(tau))
    gt = gt_mask.to(pred.dtype)
    inter = torch.minimum(pred, gt).sum(dim=(-1, -2))
    union = torch.maximum(pred, gt).sum(dim=(-1, -2))
    per = 1.0 - (inter + float(eps)) / (union + float(eps))       # [B,H]
    valid = shape_valid & sample_mask[:, None]
    return _masked_mean(per, valid)


def ellipse_safety_loss(center, a, b, theta, occ, raster_res=64, tau=10.0,
                        chunk_size=32, cvar_fraction=0.2, cvar_weight=1.0,
                        eps=1e-6, sample_mask=None):
    """Mean + CVaR of ``1 - free-area-fraction`` over the full ellipses.

    ``u_i`` is the unsafe fraction of the complete theoretical soft ellipse and
    ``L_safe = Mean(u) + lambda_CVaR * CVaR(u)`` exactly as in the report.
    """
    if occ.dim() == 3:
        occ = occ.unsqueeze(1)
    B, K = center.shape[0], center.shape[1]
    occ_r = F.adaptive_max_pool2d(occ.float(),
                                  output_size=(int(raster_res), int(raster_res)))
    free = 1.0 - occ_r[:, 0, None]
    cell_area = (2.0 / float(raster_res)) ** 2
    tau_t = torch.as_tensor(tau, device=occ.device, dtype=occ.dtype)
    soft_area_factor = F.softplus(tau_t) / tau_t
    weight = (torch.ones(B, device=center.device) if sample_mask is None
              else sample_mask.to(center.dtype))
    unsafe_chunks = []
    for start in range(0, K, int(chunk_size)):
        end = min(start + int(chunk_size), K)
        mask = ellipse_soft_mask(center[:, start:end], a[:, start:end],
                                 b[:, start:end], theta[:, start:end],
                                 int(raster_res), float(tau))
        free_cells = (mask * free).sum(dim=(-1, -2))
        full_cells = (math.pi * a[:, start:end] * b[:, start:end]
                      * soft_area_factor / cell_area)
        free_ratio = (free_cells / (full_cells + eps)).clamp(0.0, 1.0)
        unsafe_chunks.append(1.0 - free_ratio)
    unsafe = torch.cat(unsafe_chunks, dim=1)                       # [B,K]
    weighted = unsafe * weight[:, None]
    mean = weighted.sum() / weight.sum().clamp_min(1.0) / float(K)
    tail = max(1, math.ceil(K * float(cvar_fraction)))
    cvar = torch.topk(weighted, k=tail, dim=1, largest=True,
                      sorted=False).values.mean(dim=1)
    cvar = _masked_mean(cvar, weight)
    return mean + float(cvar_weight) * cvar, mean, cvar
